### ISSUE TITLE
Store URL of model and add ability to open URL from model view page

### ISSUE THREAD

**Issue by wogam** [hayden-fr/ComfyUI-Model-Manager#20]
As per title.  Thanks!

**Comment by cdb-boop** [comment]
On my dev branch I've added support for caching model urls in `.url` files beside the model.

**Comment by cdb-boop** [comment]
By default, the link button is not shown in the model preview grid. It can be turned on in the settings by selecting `Show "Open Model Url" button`.

Link in model grid:

![Screenshot 2024-09-12 031426](https://github.com/user-attachments/assets/00c1933d-2958-4730-9e58-994b8f06cb2d)

Link in model info:

![Screenshot 2024-09-12 031405](https://github.com/user-attachments/assets/7c83f14f-2f64-494d-997e-fddea29e94c3)
