### ISSUE TITLE
Small issue with firefox's drag fix

### ISSUE THREAD

**Issue by EtSL33py** [hayden-fr/ComfyUI-Model-Manager#23]
`window.screenLeft` and `window.screenTop` are subtracted from the coordinates to correct them. It works well when browser window is not maximized. When window is maximized in Windows `window.screenLeft` and `window.screenTop` are equal to -8, it adds a small offset and sometimes makes it a little difficult to drag onto a node widget

https://github.com/hayden-fr/ComfyUI-Model-Manager/blob/6f61688bd827c9e7abdb2e1f3ae34bb2ed0ce16e/web/model-manager.js#L113-L116

**Comment by cdb-boop** [comment]
Do you know why it is equal to -8? Is there some global variable/constant it is related to?

**Comment by EtSL33py** [comment]
A maximized window in Windows has a position of (-8, -8). This is Windows's way to hide a windows's borders, which in [Windows 10 are still 8px width](https://stackoverflow.com/a/42491227/27363810). Idk what happens in Windows 11
