### ISSUE TITLE
No previews thumbs

### ISSUE THREAD

**Issue by Khampol** [hayden-fr/ComfyUI-Model-Manager#25]
No previews : have to add 1 by 1 manually ?? :/ seriously ??

**Comment by cdb-boop** [comment]
I'm not sure what you mean. You can select preview images when you download a file. Are you looking for another behavior?

![download-model-tab-flux-example](https://github.com/user-attachments/assets/6e7c6979-435d-4b33-b07b-45779929ca51)

**Comment by Khampol** [comment]
I mean that I already have some checkpoint installed but no prev. is auto generate for them. 

![image](https://github.com/user-attachments/assets/ff6a3e74-8939-4fb5-8da7-7fc7eaed3624)

Is there a auto download in this case ?

**Comment by cdb-boop** [comment]
I was planning on adding one on my [dev fork](https://github.com/cdb-boop/ComfyUI-Model-Manager), now that I've added a "model info" scan in the settings.

It would do a separate scan using the downloaded model info. However, most models may have more than one images associated with it, so it would just have to grab the first image, which may or may not be the best image to use.

I could alternatively add a selection pop-up in model info, where you could manually select a preview just like when you're downloading, but it would involve a bit more engineering to get working.

**Comment by Khampol** [comment]
Oh... Strang as I manage to find this myself...
![image](https://github.com/user-attachments/assets/b85cd22c-b677-4f2f-9844-ea443935736d)
then..
![image](https://github.com/user-attachments/assets/5016ae69-3226-4429-875d-abc292f8f052)
Now checkpoint and lora galerie are full of prev. :)
Btw I also wait for your update too. Thx!

**Comment by cdb-boop** [comment]
That's part of the pysssss extension, but glad you figured it out.

**Comment by cdb-boop** [comment]
My current solution is to download model info with the `globe` icon and then select the preview you want (small image file) just like when downloading.

![Screenshot 2024-09-23 015057](https://github.com/user-attachments/assets/5640c3e7-ea5f-4cec-ad7a-78b99c253564)

**Comment by Khampol** [comment]
The globe can be the golbal button, click once and download/refresh all infos needed. Then another for edit (individually) and select image or upload as please. (same principe as Plex).

**Comment by cdb-boop** [comment]
You can also do a scan to download model info first. (It may take a while.)

![Screenshot 2024-09-23 032704](https://github.com/user-attachments/assets/ca70e248-4828-4090-9a08-e6006c010265)

**Comment by cdb-boop** [comment]
Okay, I've added a scan for downloading previews automatically. You need to first do a download model info scan, and then you do a download preview scan. I have had trouble getting uncompressed images, but I was able to alter the urls in the model info to return the full sized images (may be compressed).

Unless there is something I've overlooked or a bug, I believe this resolves the issue.

![Screenshot 2024-09-23 175649](https://github.com/user-attachments/assets/74aa3bad-a359-4380-8b90-4a05b46c4e0d)

**Comment by Khampol** [comment]
In settings I dont see what you said above?.... 😅 (i update comfy and ur plugin already..)

![image](https://github.com/user-attachments/assets/2f986697-1d9f-45ff-9e46-ce5b9ee2b653)

also a little notice, this button should be more "obvious" 

![image](https://github.com/user-attachments/assets/547df8cb-f3c7-46a7-bfd2-73a9cb71705b)

**Comment by cdb-boop** [comment]
In the custom node folder, you need to add your private Civitai API key to the `server_settings.yaml` file.

```
civitai_api_key: <KEY GOES HERE>
```

**Comment by Khampol** [comment]
Wow now it work (globally) like a charm. BTW infos include preview are there but I do not see their URL? Do i have manually add in "NOTES" ?

**Comment by cdb-boop** [comment]
Downloading model info should automatically add notes and urls (if they do not exist).

If you want to update information, you can manually download model info in the model info viewer, as if forces a hash and a download. Downloading notes fallback back to looking in the model info file for notes information.

![force redownload model info](https://github.com/user-attachments/assets/8403d198-bacf-49d4-b451-07f016f148a2)

![extracts notes from model info, will use cached](https://github.com/user-attachments/assets/6471bdfe-279a-41b9-9fbf-4893277abffb)

**Comment by Khampol** [comment]
See none of buttons you mention... update and restart comfy already.... 🤨

![image](https://github.com/user-attachments/assets/b210eb9f-a5dd-4553-83ce-91791b5836ca)

**Comment by cdb-boop** [comment]
The change was reverted. Either swap to my dev fork or wait until it is pulled again.

**Comment by Ainaemaet** [comment]
Hi there, is there a possible eta on this? I have a library of a couple hundred models I've amassed over the years, and manually downloading images for each one is just not really feasible. 

Alternatively, if I were to swap to dev just to use the function and populate everything, would the necessary data still be there if I swap back? 

Thank you for such a cool manager btw, I absolutely love it and have been waiting for something like it to come along that is more active than ComfyUI-WorkspaceManager (which has seen 1 or 2 updates in months and often goes entirely defunct for long-ish periods of time - but I understand it's a lot of work!!).

**Comment by cdb-boop** [comment]
I'm sorry. My PR was rejected on dubious grounds.

You can simply disable the main branch model manager (add `.disabled` to the end of the folder) and then download the branch. Obviously restart ComfyUI if it is up. Then you can run the scans. Make sure to do download the metadata before you try downloading the previews.

Then, you can simply remove my dev fork and remove `.disabled` from the folder and restart the application.

**Comment by darebgd** [comment]
Why has this feature been pulled out from the main branch? It worked well enough...
Also, I see more downgrades, like these buttons taken out:
![image](https://github.com/user-attachments/assets/ee167ecf-f72b-4bc7-bf6a-b0f5aef0f7f0)

If you ever get back these buttons to the main branch, I'd advise you to make the reduced panel resizable, so it doesn't always cover half of the workspace. That and remember settings, positions. Really, really great feature

**Comment by cdb-boop** [comment]
It never got pulled on the grounds that it used a single python package for markdown.

As far as I'm concerned, there have been too many performance and feature regressions and bugs that have made this extension unusable for my way of working in ComfyUI. I put a lot of care in to carefully designing and testing things. As a result I am not interested in spending the time reimplementing features in the main branch.

**Comment by hayden-fr** [comment]
The migration of the scanning model feature is expected to be carried out this week.

If there are any other features that need to be migrated or if you have any issues, please feel free to add them.

**Comment by Ainaemaet** [comment]
@hayden-fr > The migration of the scanning model feature is expected to be carried out this week.

That is _really_ great to know. As it is, for those of us with many dozens to hundreds of models the manager is a bit frustrating as you need to manually set everything so a scanning feature is essential imo. 

Thank you!! (and for your contributions as well @cdb-boop).

**Comment by vitosans** [comment]
Thank @cdb-boop - I switched to your fork and fixed all my models. I hope you stay on the project and keep contributing.

**Comment by cdb-boop** [comment]
Thanks @vitosans . I'm just busy at the moment and would need to take some time to get up to speed with Vue. Maybe in the future when things slow down.

**Comment by Ainaemaet** [comment]
@hayden-fr 

Using @cdb-boop's branch, my model previews and info are all quickly populated by what I already have in my models folders and subfolders. 

I try switching back, and none of it is retained. 

Please consider enabling us to use data that is already there in the same manner...

**Comment by Ainaemaet** [comment]
> Thanks @cdb-boop - I switched to your fork and fixed all my models. I hope you stay on the project and keep contributing.

How did you get it to retain the model info when switching back? I do a scan on @cdb-boop fork and it auto-populates with all the previews I already have in my model subfolders, but as soon as I switch back it's gone... :/

**Comment by Ainaemaet** [comment]
> The migration of the scanning model feature is expected to be carried out this week.
> 
> If there are any other features that need to be migrated or if you have any issues, please feel free to add them.

Hi @hayden-fr 

Sorry to bother you, I'm sure you're very busy with the recent talks about merging into ComfyUI proper (very cool btw). 

Is it possible to get an eta on the scanning feature? 

Thank you!
