### ISSUE TITLE
Are you interested in merging my fork?

### ISSUE THREAD

**Issue by cdb-boop** [hayden-fr/ComfyUI-Model-Manager#3]
I [forked this repo](https://github.com/cdb-boop/ComfyUI-Model-Manager) a while ago and made some large changes to the codebase. I think it's finally reached a "1.0" for core features. I'm curious if you're interested in merging the changes?

The change that I think may be most relevant to your use case is installing models. I added support to downloading from Civitai and HuggingFace, but in theory "index.json" files should still work if given a valid link, although I haven't tested it enough. Any input on how the index files are practically used is welcome.

I may still make changes to the code base, but if you're interested, I can submit a PR. Otherwise, I can register the fork with the ComfyUI-Manager instead.

**Comment by hayden-fr** [comment]
Welcome to submit

**Comment by cdb-boop** [comment]
Cool. I'll make a PR soon. I just need to add a way to set preview images.

**Comment by cdb-boop** [comment]
@hayden-fr I submitted a PR

**Comment by cdb-boop** [comment]
I was just about to give up hope. :)

**Comment by hayden-fr** [comment]
> I was just about to give up hope. :)

I'm very sorry, I'm really busy at this time.
