### ISSUE TITLE
Can't change save path

### ISSUE THREAD

**Issue by ChrisTheDBA** [hayden-fr/ComfyUI-Model-Manager#32]
When I download a model(checkpoint/lora), I cannot change the save path from the defaults '/checkpoints/0' or '/loras/0'.  

For instance, I have an SDXL folder under checkpoints, and changing the download path to '/checkpoints/SDXL/0' results in an invalid path error.

**Comment by cdb-boop** [comment]
In your case, my guess would be `/checkpoint/0/SDXL` and `/loras/0/SDXL`.

It's in the format `/model_type/directory_index/my/sub/directories`.

If you add a slash to the end, for example `/checkpoint/0/`, there should be a dropdown showing you all available subdirectories. When the dropdown is visible, you can also use arrow keys to quickly navigate.

**Comment by cdb-boop** [comment]
In your case, my guess would be `/checkpoints/0/SDXL`.

It's in the format `/<model_type>/<directory_index>/my/sub/directories`.

If you add a slash to the end, for example `/checkpoints/0/`, there should be a dropdown showing you all available subdirectories. When the dropdown is visible, you can also use arrow keys to quickly navigate.

**Comment by ChrisTheDBA** [comment]
Awesome. That worked.
