### ISSUE TITLE
Invalid cross-device link

### ISSUE THREAD

**Issue by cliffrowley** [hayden-fr/ComfyUI-Model-Manager#40]
This new method of downloading isn't working very well with containers or in general instances where models are on a different device (for example when they are shared between different interfaces).

For example:

`[Errno 18] Invalid cross-device link: '/app/custom_nodes/ComfyUI-Model-Manager/downloads/25737d65f2ed4f218fcd18133b9648f4.download' -> '/app/models/loras/dvr-dulcesa-one-piece.safetensors'`

It's a shame because it's _completely_ broken this extension for me.

**Comment by hayden-fr** [comment]
Does this issue arise when the download is completed?
