### ISSUE TITLE
IMPORT FAILED ERROR

### ISSUE THREAD

**Issue by JamieTsui** [hayden-fr/ComfyUI-Model-Manager#45]
It cannot run properly. IMPORT FAILED is displayed in the node manager. 

Console Message:
Cannot import P:\AI_Tools\ComfyUI-aki\custom_nodes\ComfyUI-Model-Manager module for custom nodes: 'Unknown user: default'

![Screenshot 2024-11-05 102001](https://github.com/user-attachments/assets/be4c7fed-df13-4c57-8cce-e0a6aa05a0e0)

**Comment by hayden-fr** [comment]
Did you use the `--multi-user` argument?

Our development progress hasn't reached this point yet. A temporary solution is to add the `default` user

**Comment by hayden-fr** [comment]
Add `"default": "default"` to `ComfyUI/user/users.json` if you have enabled `--multi-user`.

**Comment by JamieTsui** [comment]
Oh，it works，thank you so much.
