### ISSUE TITLE
Previews?

### ISSUE THREAD

**Issue by clayne** [hayden-fr/ComfyUI-Model-Manager#5]
I have preview png's for almost all my checkpoints and loras as downloaded by the a1111's civitai_helper extension but whenever I open up the model manager absolutely none of the previews are ever shown.

**Comment by cdb-boop** [comment]
Do the preview images have the same name (excluding the extensions) as the models files?

Currently, for each model, it searches for a matching image with the same name without the extension and takes the first one.

**Comment by clayne** [comment]
> Do the preview images have the same name (excluding the extensions) as the models files?
> 
> Currently, for each model, it searches for a matching image with the same name without the extension and takes the first one.

They're actually `<model>.preview.png`.. I wonder if the extra `preview` is what's throwing things off:
```
clayne@sv590:/f/stablediffusion/shared/models/checkpoints/sdxl $ ls -la artium*
-rwxr-xr-x+ 1 clayne None     449625 Feb 19 21:39 artium_v20.civitai.info
-rwxr-xr-x+ 1 clayne None       1265 Feb 19 21:39 artium_v20.json
-rwxr-xr-x+ 1 clayne None     238384 Feb 19 21:39 artium_v20.preview.png
-rw-r-xr-x+ 1 clayne None 6939255138 Feb 19 17:55 artium_v20.safetensors
```

**Comment by cdb-boop** [comment]
As long as it's standardized, that sounds okay.

The only issue is that there's a bunch of hard-coded behavior that expects `<model>.ext` in some python functions (e.i. moving models, deleting models, getting index, getting preview). I can't recall ATM if there's anything like that in the JavaScript code.

It just needs care to not create bugs, but shouldn't be too hard. I think I can look at it in the next 48 hours.

**Comment by clayne** [comment]
Looks like the SD Civitai Helper uses `<model>.preview.png` because A1111 supports both `<model>.png` and `<model>.preview.png` so it opts to use the latter:

> Extra network uses both model_file.png and model_file.preview.png as preview image. But model_file.png has higher priority, because it is created by yourself.
>
> When you don't have the higher priority one, it will use the other automatically.

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/main/README.md#preview-image

**Comment by cdb-boop** [comment]
@clayne I've added fallback support for `.preview.<extension>` preview types to my [dev branch](https://github.com/cdb-boop/ComfyUI-Model-Manager/commit/df8fb76f26dbb6c83399a1fc3e717e478a9e75bc) if you want to test it. It seems to work on my end, but my files don't use that format, so I could totally have missed something.

**Comment by clayne** [comment]
Using your checkout main branch and things work correctly! Will need to double check what https://github.com/pythongosssss/ComfyUI-Custom-Scripts looks for and determine if perhaps the best route here is either this change or an option to the sd-civitai-helper to get it to write to the more "standard" preview extensions rather than `<model>.preview.png`.

**Comment by cdb-boop** [comment]
Good to here. I would like to hear if any defaults/behaviors should change to maximize compatibility.
