### ISSUE TITLE
NPM not recognized and wont install

### ISSUE THREAD

**Issue by tpcdaz** [hayden-fr/ComfyUI-Model-Manager#52]
Got an issue here when I try to install your node. 

npm install brings back "'npm' is not recognized as an internal or external command,
operable program or batch file."

and trying to install npm with pip install npm brings back "E:\Comfy UI\ComfyUI\custom_nodes\ComfyUI-Model-Manager>pip install npm
Collecting npm
  Using cached npm-0.1.1.tar.gz (2.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\KopDa\AppData\Local\Temp\pip-install-byly9vyt\npm_9f68827f8bff462986ff983b5607dab6\setup.py", line 2, in <module>
          import npm
      ModuleNotFoundError: No module named 'npm'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

E:\Comfy UI\ComfyUI\custom_nodes\ComfyUI-Model-Manager>"

So I have no idea what to do next.

**Comment by hayden-fr** [comment]
I'm very sorry that my explanation was not perfect. The npm is the package manager of nodejs. If you want to use `npm run build` to build web dist, you need to install nodejs first.

In fact, I have already made an optimization before this. After starting ComfyUI, the extension will check the current version and download the web release file online, so you don't need to do anything.

**Comment by tpcdaz** [comment]
Ah ok thank you very much. Appreciated
