### ISSUE TITLE
fix-civitai-helper-preview breaking bug

### ISSUE THREAD

**Issue by Ainaemaet** [hayden-fr/ComfyUI-Model-Manager#58]
Hello, 

I clone or checkout to the 'fix-civitai-helper-preview' branch, ComfyUI doesn't start up. Instead I get an infinite loading spinner (class="pi pi-spinner pi-spin text-3xl opacity-30"). 

At first, I assumed perhaps things were set to auto-scan on start, but I can't see anything happening on the backend, it just appears to be stuck. 

I'm checking my files as it sits there t see if any .webp's are showing up that weren't there before, but it doesn't seem to be doing anything. 

Is 'fix-civitai-helper-preview' the branch I should be on? Or is the main branch updated to the non-destructive proper scanning method as well?

**Comment by Ainaemaet** [comment]
Ok, right as I finished that comment - it finally finished loading the UI, however when I choose Model Manager settings, everything is exactly the same and it still warns that the process is destructive (which I believe it shouldn't be on this branch?). 

At any rate, when clicking the migrate and continue on the warning, I get the same "[ComfyUI Model Manager] Migrating legacy information...
[ComfyUI Model Manager] Download model info failed: 'images'" as before. 

I don't think I'm doing anything wrong, it appears to be a problem in the migrator similar to before.

**Comment by hayden-fr** [comment]
I don't think you need to worry about migration anymore.

Your core requirement is that the preview image downloaded through `a1111-civitai-helper` cannot be displayed in `ComfyUI-Model-Manager`. This problem has been solved in the latest update. Switch to the branch main and pull.

**Comment by hayden-fr** [comment]
Or you can comment your questions and specific needs, and I will answer them for you. I will update the program if necessary.

**Comment by Ainaemaet** [comment]
@hayden-fr 

Thank you for your attention to these needs.  The extension is actually the a1111-civitai-browser-plus (https://github.com/BlafKing/sd-civitai-browser-plus). 

It is a very powerful civ browser, enabling you to browse civ models, install, update, etc. and is also very fast. Perhaps there are some things there that can help you improve this project? 

I updated to main, still no previews showing - migrate worked better than before, but barely - this time instead of an immediate "Download model info failed: 'images'", it correctly migrated the description for one of them, and then failed. 

I've decided to just go ahead with a full scan, but it is _**so slow**_ compared to @cdb-boop's fork, which I'm assuming must have something to do with the fact that his automagically has much of my already downloaded info and previews available. 



I am more than happy to provide you with any information from my own setup that you think might help you.

**Comment by Ainaemaet** [comment]
I do believe the BlafKing repo might be able to help with some things - it also seems to recognize all sorts of model data downloaded from other areas - and it is blazingly quick at downloading. Much faster than either this or cdboops fork. 

Here are pictures of the options pages, just to give you an idea: 
![Civbrowser+2](https://github.com/user-attachments/assets/a6bfc7ae-fc16-42d8-893a-70058689df01)
![Civbrowser+](https://github.com/user-attachments/assets/875e2ba8-b6d1-40b1-809b-8f7c47e37d59)


If you still have a auto1111 setup, try it out - it's amazing!!

**Comment by hayden-fr** [comment]
> it correctly migrated the description for one of them, and then failed.

No failure message?

You can add the `--verbose` parameter at startup to get detailed

**Comment by hayden-fr** [comment]
> I do believe the BlafKing repo might be able to help with some things - it also seems to recognize all sorts of model data downloaded from other areas - and it is blazingly quick at downloading. Much faster than either this or cdboops fork.

Thank you very much for your suggestions. It's truly useful to me. :)

**Comment by Ainaemaet** [comment]
> > it correctly migrated the description for one of them, and then failed.
> 
> No failure message?
> 
> You can add the `--verbose` parameter at startup to get detailed

Sounds good, I will try - thank you. 

Glad to hear that repo might be helpful. I've always been kind of baffled that nothing similar had come along for ComfyUI yet. If you can give us similar functionality while keeping it relatively lightweight... Wow that would be amazing. 🦸

**Comment by Ainaemaet** [comment]
You may also want to check out the awesome ComfyUI Lora Sidebar plugin (https://github.com/Kinglord/ComfyUI_LoRA_Sidebar) as well. 

I just gave it a try, and it not only displays super nicely - but is so blazingly fast in gathering info from Civitai (it also couldn't find my existing data, so I'm beginning to think that might be a problem with the fact I'm accessing ComfyUI from a networked PC using the --listen option? Not sure... 🤔). 

Anyhow, perhaps you could consider collaborating or just checking out that repo as well to see what you can glean that may be of use?

**Comment by Ainaemaet** [comment]
Every little bit helps. I'm still not getting things to display properly; on an attempted migration I get: 
```
[ComfyUI Model Manager] Migrating legacy information...
[ComfyUI Model Manager] Migrate description from xl13AsmodeusSFWNSFW_v22BakedVAE.safetensors
[ComfyUI Model Manager] Migrate description from -Flux-/Flux.1-Dev/artsyDream_v4FP8.safetensors
[ComfyUI Model Manager] Migrate preview image from -Flux-/Flux.1-Dev/demonCORESFWNSFW_fluxV13_956597.safetensors
[ComfyUI Model Manager] Download model info failed: 'images'
```
The 'Download missing information or preview' works - in that it does scan through all my model folders (and then some), downloads and generates the required .webp's and .md's, but (almost) none of it displays in the UI.

I'm running ComfyUI over network using the '--listen' flag, not sure if that is causing the issue - but can't see why it would be? 

Also, my model folder is symlinked from an ssd on the windows filesystem to Comfyui/models in WSL2 internally (via linux mount folder '/mnt') _but_ there should be no issue there either, as linux recognizes it as just another folder and all of the other plugins, including cdboop's fork, the auto1111 ones (in auto oc), and every other model manager plugin for ComfyUI I've found  picks them up just fine.

**Comment by Ainaemaet** [comment]
Oh, some are named with a period at the start '.' as well, because those are usually used for 'hidden folder' designations in various AI art programs to keep certain models from being shown, unless they are checked off to show those ones in options somewhere. 


I hope all that helps!!!!! :)

**Comment by hayden-fr** [comment]
Thanks for the information, I'll retest :)

**Comment by Ainaemaet** [comment]
@hayden-fr 

Everything is working good now. About the only issue is the startup time; I still think it would be preferable to not scan at startup and have a user-choice as to when to scan and whether or not to cache the model data. 

I'm assuming that's what's slowing it down. 

Aside from that though, and even still - this plugin is _amazing_ and something that was sorely missing; and I love using ComfyUI that much more now. 

Thank you!!! 🙏😊😊😊

**Comment by Ainaemaet** [comment]
Ok, yeah - after needing to load up again after a browser crash, the loading time is *really* an issue. 

Sometimes, depending on workflow - resetting comfy or opening a second or third instance is important - but the way things are now I have to wait about 5 minutes for the startup scan to finish. 

Everything else seems to work great, just this one issue!

**Comment by Ainaemaet** [comment]
Some more options would be nice, like being able to change the thumbnail preview size, and pick exact scanning locations as well.
