### ISSUE TITLE
Toggle show directory based on directory's name or type 

### ISSUE THREAD

**Issue by Hujikuio** [hayden-fr/ComfyUI-Model-Manager#63]
Whatever is easier for you if you want to add this feature. A1111/reForge/Forge has a toggle to hide the display of hidden (dot) directories with a toggle, would be nice to have this feature implemented.

**Comment by hayden-fr** [comment]
I did not find this extension (in a1111-web extensions and github). Can you provide a more specific address?

Or you can directly describe the detailed function. Do you want to use a switch to decide whether to scan folders starting with dot?
