### ISSUE TITLE
model manager gets stuck on load

### ISSUE THREAD

**Issue by rubenxito** [hayden-fr/ComfyUI-Model-Manager#76]
Hello, I'm trying to use the last node update but it always gets stuck on load (see screen capture). It happens in my local comfyui instance with many models but also in a clean comfyUI install that I've done to test the node...
![Captura desde 2024-12-06 13-46-16](https://github.com/user-attachments/assets/eff3da16-42d2-4052-bda7-07e49125bdf4)

**Comment by hayden-fr** [comment]
Does this also happen without any model?

**Comment by rn7s2** [comment]
Yes. I don't have any model (just inited ComfyUI) and same issue occurs.

![image](https://github.com/user-attachments/assets/79c3f271-51eb-49e2-a8cc-b3b015a97880)

**Comment by rubenxito** [comment]
it works, thanks!

**Comment by Jeremy8776** [comment]
Im still getting this on fresh install
