### ISSUE TITLE
Infinite Load

### ISSUE THREAD

**Issue by Jeremy8776** [hayden-fr/ComfyUI-Model-Manager#78]
Its like this till page refresh:

![image](https://github.com/user-attachments/assets/23fc5da1-8284-42f1-b4e7-02a4982177ed)

Console:
![image](https://github.com/user-attachments/assets/b77e0f13-7139-4e4c-902d-5f163479aee3)

**Comment by Ainaemaet** [comment]
Can confirm having the same issue now since latest update. 

Everything runs fine, but as soon as I click on the model manager tab, I get the regular 5 minutes of loading before it shows my models, then once the list is populated it just hangs indefinitely.

**Comment by vitosans** [comment]
Came here to report the same.

**Comment by yunwuhai** [comment]
I've rolled back the project to the previous version, and noticed that this bug no longer occurs. This leads me to suspect that the issue might have been introduced in the most recent commit.

**Comment by Jeremy8776** [comment]
Can confirm issue resolved.
