### ISSUE TITLE
Feature Request: use Markdown instead of txt

### ISSUE THREAD

**Issue by zmwv823** [hayden-fr/ComfyUI-Model-Manager#9]
markdown is more convenient and more readable.
Just a idea.

**Comment by cdb-boop** [comment]
I considered supporting other text formats, but the issue I ran into is what to do if there were multiple text-based files (e.g. json, txt, md)? If you save changes to a note, which one or ones are updated? And I'd prefer to play nice with other programs.

**Comment by cdb-boop** [comment]
No problem. If you think of a solution, feel free to reopen the issue.
